# Automatically generated by SST
# pylint: disable=all
from typing import Any

class Resource:
    class ChatInterface:
        service: str
        type: str
        url: str
    class HospitalNavigationInterfaceVpc:
        bastion: str
        type: str

